### ISSUE TITLE
React component classes must extend React.Component.

### ISSUE THREAD

**Issue by HarshaVardhanPVK** [chentsulin/react-scrolla#3]
Getting errors as 
1. React component classes must extend React.Component.
2. A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.

while using this component. Can anyone please guide me what is the exact error is and how to overcome.

**Comment by chentsulin** [comment]
Those errors caused by bugs in your code:

1.

Your components must extend React.Component:

``` js
class YourComponentName extends React.Component {

}
```

instead of:

``` js
class YourComponentName {

}
```

2.

 For some reason, your render function get undefined, an array or some invalid value as returned value:

``` js
render() {
  return undefined;
}

render() {
  return [];
}
```

Above examples do not work, so please check and print the variables to make sure them have correct value as what you expect.
